name: Build, Multi-Arch Image

on:
  # push:
  #   branches:
  #     - main
  schedule:
    - cron: '0 0 15 */2 *'
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      image_name: ${{ steps.set_output.outputs.image_name }}
    steps:
      - name: Set the Image Name
        id: set_output
        run: echo "image_name=ghcr.io/${{ github.repository }}_single-arch" >> $GITHUB_OUTPUT


  # Python 3.12 builds
  build-linux-amd64-py312:
    needs: setup
    uses: ./.github/workflows/build-image.yaml
    with:
      images: ${{ needs.setup.outputs.image_name }}-py312
      context: .
      platforms: linux/amd64
      runner-labels: "['ubuntu-latest']"
      base_image: "ubuntu:24.04"

  build-linux-arm64-py312:
    needs: setup
    uses: ./.github/workflows/build-image.yaml
    with:
      images: ${{ needs.setup.outputs.image_name }}-py312
      context: .
      platforms: linux/arm64
      runner-labels: "['self-hosted', 'Linux', 'ARM64']"
      base_image: "ubuntu:24.04"

  build-linux-armv7-py312:
    needs: setup
    uses: ./.github/workflows/build-image.yaml
    with:
      images: ${{ needs.setup.outputs.image_name }}-py312
      context: .
      platforms: linux/arm/v7
      runner-labels: "['self-hosted', 'Linux', 'ARM']"
      base_image: "ubuntu:24.04"

  # Python 3.13 builds
  build-linux-amd64-py313:
    needs: setup
    uses: ./.github/workflows/build-image.yaml
    with:
      images: ${{ needs.setup.outputs.image_name }}-py313
      context: .
      platforms: linux/amd64
      runner-labels: "['ubuntu-latest']"
      base_image: "ubuntu:24.10"

  build-linux-arm64-py313:
    needs: setup
    uses: ./.github/workflows/build-image.yaml
    with:
      images: ${{ needs.setup.outputs.image_name }}-py313
      context: .
      platforms: linux/arm64
      runner-labels: "['self-hosted', 'Linux', 'ARM64']"
      base_image: "ubuntu:24.10"

  build-linux-armv7-py313:
    needs: setup
    uses: ./.github/workflows/build-image.yaml
    with:
      images: ${{ needs.setup.outputs.image_name }}-py313
      context: .
      platforms: linux/arm/v7
      runner-labels: "['self-hosted', 'Linux', 'ARM']"
      base_image: "ubuntu:24.10"

  # Create multi-arch manifest for Python 3.12
  build-py312:
    needs:
      - setup
      - build-linux-amd64-py312
      - build-linux-arm64-py312
      - build-linux-armv7-py312
    uses: ./.github/workflows/create-manifest.yaml
    with:
      base_image: "ubuntu:24.04"
      python_version: "python3.12"
      amd64_digest: ${{ needs.build-linux-amd64-py312.outputs.digest }}
      arm64_digest: ${{ needs.build-linux-arm64-py312.outputs.digest }}
      armv7_digest: ${{ needs.build-linux-armv7-py312.outputs.digest }}
      single_arch_image_name: ${{ needs.setup.outputs.image_name }}-py312

  # Create multi-arch manifest for Python 3.13
  build-py313:
    needs:
      - setup
      - build-linux-amd64-py313
      - build-linux-arm64-py313
      - build-linux-armv7-py313
    uses: ./.github/workflows/create-manifest.yaml
    with:
      base_image: "ubuntu:24.10"
      python_version: "python3.13"
      amd64_digest: ${{ needs.build-linux-amd64-py313.outputs.digest }}
      arm64_digest: ${{ needs.build-linux-arm64-py313.outputs.digest }}
      armv7_digest: ${{ needs.build-linux-armv7-py313.outputs.digest }}
      single_arch_image_name: ${{ needs.setup.outputs.image_name }}-py313
